### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by scotticles** [pavelsr/moo-google#1]
In the 00-load.t

`BEGIN {
    use_ok('Mojo::Google') || print "Bail out!\n";
}

diag("Testing Mojo::Google $Mojo::Google::VERSION, Perl $], $^X");
`

its failing, shouldn't it say Moo::Google...

**Comment by pavelsr** [comment]
Fixed, sorry for long waiting period.

Module updated on Metacpan to [version 0.03](https://metacpan.org/pod/Moo::Google)
